src/instructor/urls.py
from django.urls import path
from .views import *


app_name = 'instructor'



urlpatterns = [

    path('update/',update,name='update'),
    path('insert/',instert,name='insert'),
    path('list/',list,name='list'),
    path('delete/',delete,name='delete'),
    path('register/',register,name='register'),

]

src/project_one/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [

    
    path('admin/', admin.site.urls),
    path('users/',include('user_auth.urls')),
    path('traniee/',include('traniee.urls')),
    path('instructor/',include('instructor.urls')),
]

src/traniee/urls.py
from django.urls import path
from .views import *



app_name='traniee'



urlpatterns = [

    path('update/',update,name='update'),
    path('insert/',instert,name='insert'),
    path('list/',traniee_list,name='listTraniee'),
    path('delete/',delete,name='delete'),
    path('register/',Trainee_register,name='Trainee-register'),

]

src/user_auth/urls.py
from .views import *
from django.urls import path





urlpatterns = [
    path('login/',login,name='login'),
    path('register/',register,name='register'),
]

src/instructor/models.py
from django.db import models

# Create your models here.




class Instructor(models.Model):

    usrnme = models.CharField(max_length=20)
    f_name = models.CharField(max_length=20)
    l_name = models.CharField(max_length=20)
    email = models.EmailField(max_length=60)
    track = models.CharField(max_length=20)
    passwd= models.CharField(max_length=8)


    def __str__(self):
        return self.f_name

src/traniee/models.py
from django.db import models

# Create your models here.



class Traniee(models.Model):

    usrnme = models.CharField(max_length=20)
    f_name = models.CharField(max_length=20)
    l_name = models.CharField(max_length=20)
    email = models.EmailField(max_length=60)
    track = models.CharField(max_length=20)
    passwd= models.CharField(max_length=8)


    def __str__(self):
        return self.f_name

src/user_auth/models.py
from django.db import models

# Create your models here.

src/instructor/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from .models import Instructor 
# Create your views here.




def list(request):
    inst = Instructor.objects.all()


    return render(request,'instructor/list.html',{'inst':inst,})



def instert(request):
    return render(request,'instructor/insert.html')



def update(request):
    return render(request,'instructor/update.html')



def delete(request):
    return render(request,'instructor/delete.html')



# views.py (inside your app)
 # Import your Instructor model

def register(request):
    if request.method == 'POST':
        # Get form data from the request
        usrnme = request.POST.get('usrnme')
        f_name = request.POST.get('f_name')
        l_name = request.POST.get('l_name')
        email = request.POST.get('email')
        track = request.POST.get('track')
        passwd = request.POST.get('passwd')

        # Create a new Instructor object and save it to the database
        instructor = Instructor(usrnme=usrnme, f_name=f_name, l_name=l_name, email=email, track=track, passwd=passwd)
        instructor.save()

        # Redirect to a success page or login page
        return redirect('list')  # Replace 'success_page' with the URL name of your success page

    return render(request, 'instructor/register.html')

src/traniee/views.py
from django.shortcuts import render,redirect
from .models import Traniee
# Create your views here.


def traniee_list(request):
    tran = Traniee.objects.all()


    return render(request,'traniee/list.html',{'tran':tran,})




def instert(request):
    return render(request,'traniee/insert.html')



def update(request):
    return render(request,'traniee/update.html')



def delete(request):
    return render(request,'traniee/delete.html')





def Trainee_register(request):
    if request.method == 'POST':
        usrnme = request.POST.get('usrnme')
        f_name = request.POST.get('f_name')
        l_name = request.POST.get('l_name')
        email = request.POST.get('email')
        track = request.POST.get('track')
        passwd = request.POST.get('passwd')

        traniee = Traniee(usrnme=usrnme, f_name=f_name, l_name=l_name, email=email, track=track, passwd=passwd)
        traniee.save()

        return redirect('listTraniee')  

    return render(request, 'traniee/register.html')

src/user_auth/views.py
from django.shortcuts import render

# Create your views here.


def register(request):
    return render(request,'user_auth/register.html')





def login(request):
    return render(request,'user_auth/login.html')

src/instructor/templates/instructor/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Instructor Sign Up</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
            integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    </head>




{% block body %}

{% endblock  %}
</html>

src/instructor/templates/instructor/delete.html
<html>

    <body>
               <h1>this is the delete page</h1>
    </body>
</html>

src/instructor/templates/instructor/insert.html
<html>
    <body>
        <h1>this is the insert page</h1>
    </body>
</html>

src/instructor/templates/instructor/list.html
<html>
    <body>
        <h1>this is the list page</h1>
        {% for instructor in inst %}
        <h3>{{ instructor.usrnme }}</h3>
        {% endfor %}
    
    </body>
</html>

src/instructor/templates/instructor/register.html
{% extends 'instructor/base.html' %}


{% block body %}
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="border-radius: 20px;">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'instructor:list' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'instructor:insert' %}">Insert</a>
            <a class="nav-item nav-link" href="{% url 'instructor:delete' %}">Delete</a>
            <a class="nav-item nav-link disabled" href="{% url 'instructor:register' %}">Register</a>
            <a class="nav-item nav-link disabled" href="{% url 'traniee:Trainee-register' %}">Trainee</a>
          </div>
        </div>
      </nav>
      

    <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-12 col-xl-11">
                    <div class="card text-black" style="border-radius: 25px;">
                        <div class="card-body p-md-5">
                            <div class="row justify-content-center">
                                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                                    <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Instructor Sign up</p>

                                    <!-- Your existing HTML form -->
                                    <form class="mx-1 mx-md-4" method="POST" action="{% url 'register' %}">
                                        {% csrf_token %}

                                        <div class="mb-4">
                                            <i class="bi bi-person-fill me-3"></i>
                                            <div class="form-group">
                                                <input type="text" id="form3Example1c" class="form-control"
                                                    name="usrnme" placeholder="Username">
                                            </div>
                                        </div>

                                        <div class="mb-4">
                                            <i class="bi bi-person-fill me-3"></i>
                                            <div class="form-group">
                                                <input type="text" id="form3Example2c" class="form-control"
                                                    name="f_name" placeholder="First Name">
                                            </div>
                                        </div>

                                        <div class="mb-4">
                                            <i class="bi bi-person-fill me-3"></i>
                                            <div class="form-group">
                                                <input type="text" id="form3Example3c" class="form-control"
                                                    name="l_name" placeholder="Last Name">
                                            </div>
                                        </div>

                                        <div class="mb-4">
                                            <i class="bi bi-envelope-fill me-3"></i>
                                            <div class="form-group">
                                                <input type="email" id="form3Example4c" class="form-control"
                                                    name="email" placeholder="Your Email">
                                            </div>
                                        </div>

                                        <div class="mb-4">
                                            <i class="bi bi-lock-fill me-3"></i>
                                            <div class="form-group">
                                                <input type="password" id="form3Example5c" class="form-control"
                                                    name="passwd" placeholder="Password">
                                            </div>
                                        </div>


                                        <div class="mb-4">
                                            <i class="bi bi-person-fill me-3"></i>
                                            <div class="form-group">
                                                <input type="text" id="form3Example7c" class="form-control" name="track"
                                                    placeholder="Track">
                                            </div>
                                        </div>


                                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                            <button type="submit" class="btn btn-primary btn-lg">Register</button>
                                        </div>

                                    </form>

                                </div>
                                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
                                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                                        class="img-fluid" alt="Sample image">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Add Bootstrap JavaScript (Optional) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.5.0/dist/js/bootstrap.min.js"></script>

</body>
{% endblock body %}

src/instructor/templates/instructor/update.html
<html>
    <body>
        <h1>this is the update page</h1>
    </body>
</html>

src/traniee/templates/traniee/delete.html
<html>
    <body>
        <h1>this is the delete page</h1>
    </body>
</html>

src/traniee/templates/traniee/insert.html
<html>
    <body>
        <h1>this is the insert page</h1>
    </body>
</html>

src/traniee/templates/traniee/list.html
<html>
    <body>
        <h1>All Traines</h1>
        {% for trainee in tran %}
        <h3>{{ trainee.usrnme }}</h3>
        {% endfor %}
    
    </body>
</html>

src/traniee/templates/traniee/register.html
{% extends 'instructor/base.html' %}


{% block body %}
<body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="border-radius: 20px;">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'traniee:listTraniee' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'traniee:insert' %}">Insert</a>
            <a class="nav-item nav-link" href="{% url 'traniee:delete' %}">Delete</a>
            <a class="nav-item nav-link disabled" href="{% url 'traniee:Trainee-register' %}">Register</a>
            <a class="nav-item nav-link disabled" href="{% url 'instructor:register' %}">Insturctor</a>

          </div>
        </div>
      </nav>
      

    <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-12 col-xl-11">
                    <div class="card text-black" style="border-radius: 25px;">
                        <div class="card-body p-md-5">
                            <div class="row justify-content-center">
                                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">

                                    <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Traniee Sign up</p>

                                    <!-- Your existing HTML form -->
                                    <form class="mx-1 mx-md-4" method="POST" action="{% url 'traniee:Trainee-register' %}">
                                        {% csrf_token %}

                                        <div class="mb-4">
                                            <i class="bi bi-person-fill me-3"></i>
                                            <div class="form-group">
                                                <input type="text" id="form3Example1c" class="form-control"
                                                    name="usrnme" placeholder="Username">
                                            </div>
                                        </div>

                                        <div class="mb-4">
                                            <i class="bi bi-person-fill me-3"></i>
                                            <div class="form-group">
                                                <input type="text" id="form3Example2c" class="form-control"
                                                    name="f_name" placeholder="First Name">
                                            </div>
                                        </div>

                                        <div class="mb-4">
                                            <i class="bi bi-person-fill me-3"></i>
                                            <div class="form-group">
                                                <input type="text" id="form3Example3c" class="form-control"
                                                    name="l_name" placeholder="Last Name">
                                            </div>
                                        </div>

                                        <div class="mb-4">
                                            <i class="bi bi-envelope-fill me-3"></i>
                                            <div class="form-group">
                                                <input type="email" id="form3Example4c" class="form-control"
                                                    name="email" placeholder="Your Email">
                                            </div>
                                        </div>

                                        <div class="mb-4">
                                            <i class="bi bi-lock-fill me-3"></i>
                                            <div class="form-group">
                                                <input type="password" id="form3Example5c" class="form-control"
                                                    name="passwd" placeholder="Password">
                                            </div>
                                        </div>


                                        <div class="mb-4">
                                            <i class="bi bi-person-fill me-3"></i>
                                            <div class="form-group">
                                                <input type="text" id="form3Example7c" class="form-control" name="track"
                                                    placeholder="Track">
                                            </div>
                                        </div>


                                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                            <button type="submit" class="btn btn-primary btn-lg">Register</button>
                                        </div>

                                    </form>

                                </div>
                                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
                                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                                        class="img-fluid" alt="Sample image">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Add Bootstrap JavaScript (Optional) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.5.0/dist/js/bootstrap.min.js"></script>

</body>
{% endblock body %}

src/traniee/templates/traniee/update.html
<html>
    <body>
        <h1>this is the update page</h1>
    </body>
</html>

src/user_auth/templates/user_auth/login.html
<!DOCTYPE html>

<head>
    <title>Login</title>
</head>
<body>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        <div >
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>
        </div>
        <div >
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
        </div>
        <div >
            <button type="submit">Login</button>
        </div>
    </form>
</body>
</html>

src/user_auth/templates/user_auth/register.html
<!DOCTYPE html>
<head>
    <title>Sign Up</title>
</head>
<body>
    <h2>Sign Up</h2>
    <form method="post" action={% url 'login' %}>
        {% csrf_token %}
        <div >
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" required>
        </div>
        <div >
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>
        </div>
        <div >
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" required>
        </div>
        <div >
            <button type="submit">Sign Up</button>
        </div>
    </form>
</body>
</html>